name:                warp-tls-uid
version:             0.2.0.5
github:              "YoshikuniJujo/warp-tls-uid"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143[at]nifty.ne.jp"
copyright:           "2018 Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            set group and user id before running server
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/warp-tls-uid#readme>

ghc-options:
- -Wall
- -fno-warn-tabs

dependencies:
- base >= 4.7 && < 5
- bytestring
- network
- wai
- warp
- warp-tls
- unix
- streaming-commons

library:
  source-dirs: src

tests:
  warp-tls-uid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-tls-uid
