name:                warp-tls-uid
version:             0.2.0.0
github:              "githubuser/warp-tls-uid"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/warp-tls-uid#readme>

ghc-options:
- -Wall
- -fno-warn-tabs

dependencies:
- base >= 4.7 && < 5
- bytestring
- network
- wai
- warp
- warp-tls
- unix
- streaming-commons

library:
  source-dirs: src

tests:
  warp-tls-uid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-tls-uid
